#!/bin/tcsh -f
echo "-------------------------------------------------------------------"
echo "------------------- TCL WORKSHOP - Shreyas-------------------------"
echo "-------------------------------------------------------------------"

set my_work_dir = `pwd`

#------------------------------------------------------------------------
#---------------------------TOOL INITIALIZATION--------------------------
#------------------------------------------------------------------------


if ($#argv != 1) then
	echo " Info: Please provide a csv file "
	exit 1
endif

if (! -f $argv[1] || $argv[1] == "-help")then
	if ($argv[1] != "-help")then
		echo "ERROR: Could not find the file $argv[1]. Exiting..."
		exit 1
	else
		echo "User Manual will be printed on how to use this tool"
		exit 1
	endif
else
	tclsh vsdsynth.tcl $argv[1]
endif

